sonar.exclusions=\
  **/*.min.js,\
  **/resources/Scripts/date.format.js,\
  **/resources/Scripts/fullcalendar.js,\
  **/resources/Scripts/gcal.js,\
  **/resources/Scripts/jquery*.js,\
  **/resources/Scripts/json2.js,\
  **/resources/Scripts/opentip-jquery-excanvas.js,\
  **/resources/Scripts/timepicker.js,\
  **/resources/Scripts/jqPlot-plugins/**,\
  **/resources/TableTools/**,\
  **/target/**
