# Test omgeving configuratie
environment=test

# Database
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}

# Logging (uitgebreider in test)
log.level=DEBUG

# Testdata mag worden gebruikt
allow.test.data=true
